### ISSUE TITLE
Unable to use xxh on Windows

### ISSUE THREAD

**Issue by SamLukeYes** [xxh/xxh#184]
**Local OS (where xxh is installed):** Windows 11
**Destination host OS:** --
**xxh version:** 0.8.14
**xxh-plugins installed:** --

**Steps to Reproduce**
1. Run `xpip install xxh-xxh` in Xonsh
2. Run `which xxh` in Xonsh
```
C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\xxh
```
3. Run `xxh` in Xonsh
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: 'xxh'
```

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by SamLukeYes** [comment]
It is still unusable with those workarounds. When I actually try to connect to a remote server, xxh crashes with `AttributeError: module 'pexpect' has no attribute 'spawn'`. Maybe related to https://github.com/pexpect/pexpect/issues/321#issuecomment-174547577.

BTW, I ran into this issue on my working computer, and I'm not going to do further investigation on the same device, for InfoSec concerns. Maybe I'll try to reproduce it on my personal device when I have time. TBF, I only use Windows at work 🤣

**Comment by SamLukeYes** [comment]
>It is still unusable with those workarounds. When I actually try to connect to a remote server, xxh crashes with AttributeError: module 'pexpect' has no attribute 'spawn'. Maybe related to https://github.com/pexpect/pexpect/issues/321#issuecomment-174547577.

OK, I can reproduce it with wine.

Steps to reproduce:

- Install Python 3.11.9 with the official installer in a wineprefix
- `ln -s $(which ssh) $WINEPREFIX/drive_c/windows/system32/ssh.exe`
- Run cmd in the wineprefix
  - `pip install xxh-xxh`
  - `python C:\users\username\AppData\Local\Programs\Python\Python311\Scripts\xxh somehost`

Output:

```
File already exists.

File already exists.

Create sample config file in C:\users\yes\.xxh\.config\xxh\config.xxhc
File already exists.

File already exists.

File already exists.

File already exists.

File already exists.

Traceback (most recent call last):
  File "C:\users\yes\AppData\Local\Programs\Python\Python311\Scripts\xxh", line 11, in <module>
    xxh.main()
  File "C:\users\yes\AppData\Local\Programs\Python\Python311\Lib\site-packages\xxh_xxh\xxh.py", line 836, in main
    host_info = self.get_host_info()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\users\yes\AppData\Local\Programs\Python\Python311\Lib\site-packages\xxh_xxh\xxh.py", line 320, in get_host_info
    pr = self.pssh(cmd)
         ^^^^^^^^^^^^^^
  File "C:\users\yes\AppData\Local\Programs\Python\Python311\Lib\site-packages\xxh_xxh\xxh.py", line 105, in pssh
    sess = pexpect.spawn(cmd)
           ^^^^^^^^^^^^^
AttributeError: module 'pexpect' has no attribute 'spawn'
```

Also, an unexpected `-p` folder appears in the current working directory.
