### ISSUE TITLE
Unknown answer from host when getting realpath for directory {host_xxh_home}

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh#69]
**Local OS (where xxh is installed): Ubuntu 16.04.6 LTS**
**Destination host OS: Red Hat 4.4.7-18 GCC**
**xxh version: xxh/0.6.10**
**xxh-plugins installed: none**

**Steps to Reproduce**
1. I run `xxh hostname`
<details><summary>2. The output log: CLICK to see collapsed text</summary>
<p>

```bash
$ xxh redhathostname
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/xxh", line 14, in <module>
    xxh.main()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/xxh_xxh/xxh.py", line 669, in main
    self.eeprint(f'Unknown answer from host when getting realpath for directory {host_xxh_home}')
UnboundLocalError: local variable 'host_xxh_home' referenced before assignment
```

</p>
</details>
3. What is the problem
Getting error:

> Unknown answer from host when getting realpath for directory {host_xxh_home}

`xxh` then exits.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by frederickjh** [comment]
I am also seeing this with a different host that is also Red Hat but a different version
```bash
$ uname -r
3.10.0-1062.1.2.el7.x86_64
```
Looks to be Red Hat 7.

**Comment by anki-code** [comment]
Thanks! I see two issues: 
1. variable referenced before assignment - I've fixed this
2. for some reason `xxh_home_realpath` is empty

Could you please give me the result of `xxh hostname +vv` the part beginning from `Host info:`?

**Comment by anki-code** [comment]
I've added the check that `realpath` exists and using `dirname` if not. Please update your xxh to 0.6.11 and try again.

**Comment by frederickjh** [comment]
OK, I think this issue is solved but now I have run into the xxh/xxh-shell-fish-appimage#2 issue with glibc.

```bash
$ xxh hostname
squidix:/home/username/.xxh/xxh/shells/xxh-shell-fish-appimage not found. Install xxh-shell-fish-appimage? [Y/n] y
Install xxh-shell-fish-appimage to squidix:/home/username/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-fish-appimage on squidix
./fish: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./fish)
./fish: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./fish)
```
Thanks!

**Comment by frederickjh** [comment]
I tested with the newest version and with the new AppImage you built and it is not successful with the following error: **/home/remoteusername/.xxh/xxh/shells/xxh-shell-fish/build/entrypoint.sh: line 78: realpath: command not found**

> Could you please give me the result of xxh hostname +vv the part beginning from Host info:? This should appears before exception.
<details><summary>CLICK ME to see collapsed debug output</summary>
<p>

```bash
Host info:
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /home/localusername/.ssh/config
debug1: /home/localusername/.ssh/config line 7: Applying options for *
debug1: /home/localusername/.ssh/config line 154: Applying options for squidix
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/dev/shm/remoteusername@server.example.net-####" does not exist
debug1: Connecting to server.example.net [##.##.##.##] port ####.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /home/localusername/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/localusername/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
debug1: Authenticating to server.example.net:#### as 'remoteusername'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-rsa SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXX
debug1: Host '[server.example.net]:####' is known and matches the RSA host key.
debug1: Found key in /home/localusername/.ssh/known_hosts:124
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/localusername/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to server.example.net ([##.##.##.##]:####).
debug1: setting up multiplex master socket
debug1: channel 0: new [/dev/shm/remoteusername@22server.example.net-####]
debug1: control_persist_detach: backgrounding master process
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: id
debug1: multiplexing control connection
debug1: channel 1: new [mux-control]
debug1: channel 2: new [client-session]
debug1: Requesting authentication agent forwarding.
debug1: Sending environment.
debug1: Sending env LC_PAPER = de_CH.UTF-8
debug1: Sending env LC_ADDRESS = de_CH.UTF-8
debug1: Sending env LC_MONETARY = de_CH.UTF-8
debug1: Sending env LC_NUMERIC = de_CH.UTF-8
debug1: Sending env LC_TELEPHONE = de_CH.UTF-8
debug1: Sending env LC_IDENTIFICATION = de_CH.UTF-8
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending env LC_MEASUREMENT = de_CH.UTF-8
debug1: Sending env LC_TIME = de_CH.UTF-8
debug1: Sending env LC_NAME = de_CH.UTF-8
debug1: Sending command: bash -s
debug1: mux_client_request_session: master session id: 2
xxh_home_realpath=/home/remoteusername/.xxh
xxh_version=0.6.14
xxh_shell_exists=1
xxh_home_writable=1
xxh_parent_home_writable=1
rsync=/usr/bin/rsync
scp=/usr/bin/scp
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
shell=
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
RUN SHELL COMMAND: LC_TIME=POSIX LC_MONETARY=POSIX LC_ADDRESS=POSIX LC_IDENTIFICATION=POSIX LC_MEASUREMENT=POSIX LC_NAME=POSIX LC_NUMERIC=POSIX LC_PAPER=POSIX LC_TELEPHONE=POSIX  ssh -v -o StrictHostKeyChecking=yes squidix -t 'bash /home/remoteusername/.xxh/xxh/shells/xxh-shell-fish/build/entrypoint.sh   -v 2 '
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /home/localusername/.ssh/config
debug1: /home/localusername/.ssh/config line 7: Applying options for *
debug1: /home/localusername/.ssh/config line 154: Applying options for squidix
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
/home/remoteusername/.xxh/xxh/shells/xxh-shell-fish/build/entrypoint.sh: line 78: realpath: command not found
```

</p>
</details>

I checked and the `dirname` command is available on that server.

**Comment by anki-code** [comment]
@frederickjh I've fixed it now. Please try again:
```
xxh +RI xxh-shell-fish
xxh myhost +s xxh-shell-fish
```

**Comment by anki-code** [comment]
Also I've replaced `realpath` to `dirname` in all xxh repos.

**Comment by frederickjh** [comment]
So that works, but it leaves me in the `build` folder.

```bash
$ xxh hostname
remoteuser@server.example.net /home/remoteuser/.xxh/xxh/shells/xxh-shell-fish/build
```
On one of my other servers it works but they have locked down the permissions on `~/.config`.
```bash
drwx--s--x 3 root      remoteuser   19 Mär 19 09:41 .config
```
so, fish configuration does not work. Not sure why they even bothered to make the group name the username group if they give you no permissions for the directory.

In any case I think we have this solved so I am going to close it.

**Comment by anki-code** [comment]
Thank you for detailed reports!

> So that works, but it leaves me in the build folder.

Fixed. Please update:
```
xxh +RI xxh-shell-fish
xxh myhost +s xxh-shell-fish +if
```

> In any case I think we have this solved

Am I right that it works on all your servers without GLIBC errors and warnings?

**Comment by frederickjh** [comment]
xxh is now working all my test hosts. There are still some issues to work out but no warning or errors. I think we are down to Fish configuration.
